# Generated by Django 4.1.7 on 2023-02-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='images/%y/$m//$d/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дерева')),
                ('thickness', models.CharField(blank=True, help_text='мм', max_length=10)),
                ('grade', models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True, verbose_name='Сорт')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, choices=[('BYN', 'byn')], max_length=20, null=True, verbose_name='Сорт')),
                ('unit', models.CharField(choices=[('m3', 'м.куб.')], default='m3', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
