# Generated by Django 4.1.7 on 2023-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='currency',
            field=models.CharField(blank=True, choices=[('BYN', 'byn')], max_length=20, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='grade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название пиломатериалов'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='thickness',
            field=models.CharField(blank=True, help_text='мм', max_length=10, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='unit',
            field=models.CharField(choices=[('m3', '1м.куб.')], default='m3', max_length=10, verbose_name='Количество'),
        ),
    ]
