# Generated by Django 4.1.7 on 2023-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_keyword_alter_category_image_alter_wood_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wood',
            name='is_published',
        ),
        migrations.AddField(
            model_name='wood',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
